import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProductRail } from "@/components/features/catalog/ProductRail";
import { fetchStoreBySlug, fetchStoreProducts } from "@/services/stores";
import { fetchStoreSoldFeedProducts } from "@/services/products";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const store = await fetchStoreBySlug(slug).catch(() => null); return store ? { title: store.name, description: store.description.slice(0, 160), alternates: { canonical: `/stores/${encodeURIComponent(slug)}` } } : {}; }
export default async function MobileStorePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const store = await fetchStoreBySlug(slug); if (!store) notFound(); const [fixed, auctions, soldFixed, soldAuctions] = await Promise.all([fetchStoreProducts(store.id,"fixed"),fetchStoreProducts(store.id,"auction"),fetchStoreSoldFeedProducts({storeId:store.id,saleType:"fixed"}),fetchStoreSoldFeedProducts({storeId:store.id,saleType:"auction"})]); return <div><section className="-mx-4 flex min-h-[300px] flex-col justify-between bg-[var(--store-card-1)] p-6"><div><p className="eyebrow">센터몰 · 센터 소개</p><h1 className="mt-16 text-4xl font-black tracking-[-.08em]">{store.name}</h1></div><div><p className="max-w-md text-sm leading-6">{store.description}</p><p className="mt-3 text-xs text-muted">판매·배송·상품 문의는 이 센터가 직접 담당합니다.</p><div className="mt-5 flex gap-4"><Link className="text-xs font-bold underline" href={`/m/chat?store=${store.id}`}>센터 문의</Link><Link className="text-xs font-bold underline" href="/m/shop">전체 상품</Link></div></div></section><ProductRail basePath="/m" eyebrow="센터몰 · 판매 중" href="/m/shop" products={fixed} surface="mobile" title="즉시구매 상품" /><ProductRail basePath="/m" eyebrow="센터몰 · 경매" href="/m/feed" products={auctions} surface="mobile" title="진행 중 경매" /><ProductRail basePath="/m" eyebrow="센터몰 · 판매완료" href="/m/sold" products={[...soldFixed,...soldAuctions]} surface="mobile" title="판매완료 상품" /></div>; }
