"use client";
import { SlidersHorizontal, X } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { PremiumDialog } from "@/components/ui/PremiumDialog";

export function ShopFilterDrawer({ basePath = "/shop" }: { basePath?: string }) {
  const router=useRouter();const current=useSearchParams();const[open,setOpen]=useState(false);const[gender,setGender]=useState(current.get("gender")??"all");const[grade,setGrade]=useState(current.get("grade")??"all");const[brand,setBrand]=useState(current.get("brand")??"");const[sort,setSort]=useState(current.get("sort")??"latest");
  const apply=()=>{const params=new URLSearchParams(current.toString());[["gender",gender],["grade",grade],["brand",brand.trim()],["sort",sort]].forEach(([key,value])=>value&&value!=="all"?params.set(key,value):params.delete(key));router.push(`${basePath}${params.size?`?${params}`:""}`);setOpen(false)};
  return <><button aria-haspopup="dialog" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-zinc-700 bg-zinc-900 px-4 text-xs font-black text-zinc-100 hover:border-amber-500 focus-visible:ring-2 focus-visible:ring-amber-500" onClick={()=>setOpen(true)} type="button"><SlidersHorizontal size={15}/> 상세 필터</button><PremiumDialog labelledBy="shop-filter-title" onClose={()=>setOpen(false)} open={open} panelClassName="max-w-lg"><header className="flex items-center justify-between border-b border-line p-5"><h2 className="text-xl font-black" id="shop-filter-title">아카이브 상세 필터</h2><button aria-label="필터 닫기" className="grid size-11 place-items-center" onClick={()=>setOpen(false)} type="button"><X/></button></header><div className="space-y-5 p-5"><label className="block text-xs font-bold">성별<select className="mt-2 h-12 w-full rounded-xl border border-line bg-paper px-3" onChange={e=>setGender(e.target.value)} value={gender}><option value="all">전체</option><option value="남성">MEN</option><option value="여성">WOMEN</option><option value="공용">UNISEX</option></select></label><label className="block text-xs font-bold">브랜드 검색<input className="mt-2 h-12 w-full rounded-xl border border-line bg-paper px-3" onChange={e=>setBrand(e.target.value)} placeholder="브랜드명" value={brand}/></label><label className="block text-xs font-bold">컨디션<select className="mt-2 h-12 w-full rounded-xl border border-line bg-paper px-3" onChange={e=>setGrade(e.target.value)} value={grade}><option value="all">전체 등급</option><option value="S">Grade S</option><option value="A">Grade A</option><option value="B">Grade B</option></select></label><label className="block text-xs font-bold">정렬<select className="mt-2 h-12 w-full rounded-xl border border-line bg-paper px-3" onChange={e=>setSort(e.target.value)} value={sort}><option value="latest">최신순</option><option value="price-asc">낮은 가격순</option><option value="price-desc">높은 가격순</option><option value="condition">컨디션 우수순</option></select></label><button className="h-13 w-full rounded-xl bg-amber-500 font-black text-zinc-950" onClick={apply} type="button">필터 적용하기</button></div></PremiumDialog></>;
}
