"use client";

import { CircleCheck, Clock3, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { CatalogImage } from "@/components/ui/CatalogImage";

interface Item { order_id: string; unit_price: number; payment_status: string; products?: { title: string; image_urls: string[] } | null; commerce_orders?: { total: number; status: string; created_at: string } | null; }
interface Transfer { order_id: string; status: string; expected_amount: number; bank_name_snapshot: string; requested_at: string; }
export function OperatorOrdersConsole() {
  const [token, setToken] = useState<string | null>(null); const [items, setItems] = useState<Item[]>([]); const [transfers, setTransfers] = useState<Transfer[]>([]); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async (accessToken: string | null) => { if (!accessToken) return; const response = await fetch("/api/operator/orders", { headers: { Authorization: `Bearer ${accessToken}` }, cache: "no-store" }); const payload = await response.json() as { items?: Item[]; transfers?: Transfer[]; error?: string }; if (!response.ok) throw new Error(payload.error ?? "주문을 불러오지 못했습니다."); setItems(payload.items ?? []); setTransfers(payload.transfers ?? []); }, []);
  useEffect(() => { void (async () => { try { const session = (await getSupabaseBrowserClient().auth.getSession()).data.session; setToken(session?.access_token ?? null); if (session) await load(session.access_token); } catch (error) { setNotice(error instanceof Error ? error.message : "주문을 불러오지 못했습니다."); } })(); }, [load]);
  const confirm = async (orderId: string) => { if (!token) return; setBusy(true); try { const response = await fetch(`/api/operator/orders/${orderId}/confirm`, { method: "POST", headers: { Authorization: `Bearer ${token}` } }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "입금을 확인하지 못했습니다."); await load(token); } catch (error) { setNotice(error instanceof Error ? error.message : "입금을 확인하지 못했습니다."); } finally { setBusy(false); } };
  const awaiting = transfers.filter((transfer) => transfer.status === "awaiting_transfer"); const confirmed = transfers.filter((transfer) => transfer.status === "confirmed");
  return <div className="space-y-8"><div className="border-b border-ink pb-6"><p className="eyebrow text-muted">OPERATOR / ORDERS</p><h1 className="mt-3 text-4xl font-black tracking-[-.08em]">입금·주문 처리</h1><p className="mt-3 text-sm text-muted">내 숍 상품에 대한 결제 상태만 표시됩니다.</p></div>{notice && <div className="border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-700">{notice}</div>}<div className="grid gap-4 md:grid-cols-3"><div className="border border-line p-5"><Clock3 size={17} /><p className="mt-7 text-xs text-muted">입금 확인 대기</p><p className="mt-2 font-mono text-3xl font-bold">{awaiting.length}</p></div><div className="border border-line p-5"><CircleCheck size={17} /><p className="mt-7 text-xs text-muted">확인 완료</p><p className="mt-2 font-mono text-3xl font-bold">{confirmed.length}</p></div><div className="border border-line bg-ink p-5 text-paper"><p className="eyebrow text-zinc-400">ORDER LINES</p><p className="mt-7 font-mono text-3xl font-bold">{items.length}</p><p className="mt-2 text-xs text-zinc-400">내 숍 상품 라인</p></div></div><div className="flex justify-end"><button className="flex items-center gap-2 text-xs underline" onClick={() => void load(token)} type="button"><RefreshCw size={13} /> 새로고침</button></div><div className="divide-y divide-line border-y border-line">{transfers.map((transfer) => { const line = items.find((item) => item.order_id === transfer.order_id); return <div className="flex flex-col justify-between gap-4 py-5 md:flex-row md:items-center" key={transfer.order_id}><div className="flex items-center gap-4"><CatalogImage alt="" className="size-16 object-cover" src={line?.products?.image_urls?.[0] ?? ""} /><div><p className="text-sm font-bold">{line?.products?.title ?? "통합 주문"}</p><p className="mt-1 text-xs text-muted">주문 {transfer.order_id} · {transfer.bank_name_snapshot}</p></div></div><div className="flex items-center gap-6"><span className="text-right"><span className="block text-[10px] text-muted">입금 금액</span><strong className="font-mono text-sm">{transfer.expected_amount.toLocaleString("ko-KR")}원</strong></span>{transfer.status === "awaiting_transfer" ? <button className="h-10 border border-ink px-4 py-3 text-xs font-bold disabled:opacity-40" disabled={busy} onClick={() => void confirm(transfer.order_id)} type="button">입금 확인</button> : <span className="text-xs font-bold text-emerald-700">확인 완료</span>}</div></div>; })}{transfers.length === 0 && <p className="py-16 text-center text-sm text-muted">처리할 수동이체 주문이 없습니다.</p>}</div></div>;
}
