"use client";

import Link from "next/link";
import { ArrowUpRight, Clock3, Package, Plus, Truck, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { CatalogImage } from "@/components/ui/CatalogImage";

interface Product { id: string; title: string; sale_type: string; current_price: number; image_urls: string[]; status: string; }
export function OperatorConsole() {
  const [products, setProducts] = useState<Product[]>([]); const [orders, setOrders] = useState(0); const [shipping, setShipping] = useState(0); const [members, setMembers] = useState(0); const [notice, setNotice] = useState("");
  useEffect(() => { void (async () => { try { const session = (await getSupabaseBrowserClient().auth.getSession()).data.session; if (!session) return; const headers = { Authorization: `Bearer ${session.access_token}` }; const [productResponse, orderResponse, shippingResponse, memberResponse] = await Promise.all([fetch("/api/operator/products", { headers, cache: "no-store" }), fetch("/api/operator/orders", { headers, cache: "no-store" }), fetch("/api/operator/shipping", { headers, cache: "no-store" }), fetch("/api/operator/members?limit=500", { headers, cache: "no-store" })]); const productData = await productResponse.json() as { products?: Product[] }; const orderData = await orderResponse.json() as { transfers?: { status: string }[] }; const shippingData = await shippingResponse.json() as { requests?: unknown[] }; const memberData = await memberResponse.json() as { members?: unknown[] }; if (!productResponse.ok) throw new Error("운영자 권한을 확인할 수 없습니다."); setProducts(productData.products ?? []); setOrders(orderData.transfers?.filter((transfer) => transfer.status === "awaiting_transfer").length ?? 0); setShipping(shippingData.requests?.length ?? 0); setMembers(memberData.members?.length ?? 0); } catch (error) { setNotice(error instanceof Error ? error.message : "운영자 데이터를 불러오지 못했습니다."); } })(); }, []);
  const stats = [["공개 상품", products.filter((product) => product.status === "active").length, Package], ["입금 확인 대기", orders, Clock3], ["배송 요청", shipping, Truck], ["회원 디렉터리", members, Users]] as const;
  return <div className="space-y-10"><div className="flex flex-row items-end justify-between gap-5 border-b border-ink pb-7"><div><p className="eyebrow text-muted">OPERATOR / CONTROL ROOM</p><h1 className="mt-3 text-4xl font-black tracking-[-0.08em]">운영자 센터</h1><p className="mt-3 text-sm text-muted">내 숍의 실제 상품·회원·주문·배송을 확인합니다.</p></div><Link className="flex items-center gap-2 bg-ink px-5 py-3 text-xs font-bold text-paper" href="/operator/products"><Plus size={15} /> 상품 등록</Link></div>{notice && <div className="border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-700">{notice}</div>}<div className="grid grid-cols-4 gap-px border border-line bg-line">{stats.map(([label, value, Icon]) => <div className="bg-paper p-5" key={label}><Icon size={17} /><p className="mt-7 text-xs text-muted">{label}</p><p className="mt-2 font-mono text-3xl font-bold">{value}</p></div>)}</div><div className="grid grid-cols-[1.25fr_.75fr] gap-10"><section><div className="mb-4 flex items-end justify-between border-b border-ink pb-4"><div><p className="eyebrow text-muted">MY STORE / PRODUCTS</p><h2 className="mt-2 text-xl font-black">내 숍 상품</h2></div><Link className="flex items-center gap-1 text-xs font-bold underline" href="/operator/products">전체 관리 <ArrowUpRight size={14} /></Link></div><div className="divide-y divide-line border-y border-line">{products.slice(0, 8).map((product) => <div className="flex items-center gap-4 py-4" key={product.id}><CatalogImage alt="" className="size-16 object-cover" src={product.image_urls?.[0] ?? ""} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{product.title}</p><p className="mt-1 text-xs text-muted">{product.sale_type === "fixed" ? "즉시구매" : "경매"} · {product.current_price.toLocaleString("ko-KR")}원</p></div><span className="border border-line px-2 py-1 text-[10px] font-bold">{product.status}</span></div>)}{products.length === 0 && <p className="py-12 text-center text-sm text-muted">등록된 상품이 없습니다.</p>}</div></section><section className="border border-line bg-surface p-6"><p className="eyebrow text-muted">TODAY / CHECKLIST</p><div className="mt-7 space-y-5 text-xs"><Link className="flex gap-3 underline" href="/operator/products">상품 이미지와 실측 확인 <ArrowUpRight size={14} /></Link><Link className="flex gap-3 underline" href="/operator/members">회원 상태·배송 이용권 관리 <ArrowUpRight size={14} /></Link><Link className="flex gap-3 underline" href="/operator/orders">입금 확인 업무 열기 <ArrowUpRight size={14} /></Link><Link className="flex gap-3 underline" href="/operator/shipping">배송 요청 송장 입력 <ArrowUpRight size={14} /></Link><Link className="flex gap-3 underline" href="/operator/chat">상담 메시지 답변 <ArrowUpRight size={14} /></Link></div></section></div></div>;
}
