"use client";

import { Download, Truck } from "lucide-react";
import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

interface RequestRow { request_id: string; item_count: number; product_ids: string[]; requested_at: string; status: string; tracking_number: string | null; courier: string | null; address_snapshot: Record<string, unknown>; }
export function OperatorShippingConsole() {
  const [token, setToken] = useState<string | null>(null); const [requests, setRequests] = useState<RequestRow[]>([]); const [notice, setNotice] = useState(""); const [forms, setForms] = useState<Record<string, { courier: string; tracking: string }>>({});
  const load = async (accessToken?: string) => { const current = accessToken ?? token; if (!current) return; const response = await fetch("/api/operator/shipping", { headers: { Authorization: `Bearer ${current}` }, cache: "no-store" }); const payload = await response.json() as { requests?: RequestRow[]; error?: string }; if (!response.ok) throw new Error(payload.error ?? "배송 목록을 불러오지 못했습니다."); setRequests(payload.requests ?? []); };
  useEffect(() => { void (async () => { try { const session = (await getSupabaseBrowserClient().auth.getSession()).data.session; setToken(session?.access_token ?? null); if (session) await load(session.access_token); } catch (error) { setNotice(error instanceof Error ? error.message : "배송 목록을 불러오지 못했습니다."); } })(); }, []);
  const ship = async (requestId: string) => { if (!token) return; const form = forms[requestId]; if (!form?.courier || !form.tracking) return; try { const response = await fetch("/api/operator/shipping", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ requestId, courier: form.courier, trackingNumber: form.tracking }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "배송 상태를 변경하지 못했습니다."); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "배송 상태를 변경하지 못했습니다."); } };
  const download = () => { const csv = ["request_id,item_count,requested_at,status,product_ids", ...requests.map((row) => [row.request_id, row.item_count, row.requested_at, row.status, row.product_ids.join("|")].map((value) => `"${String(value).replaceAll('"', '""')}"`).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "ninety-nine-shipping.csv"; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-8"><div className="border-b border-ink pb-6"><p className="eyebrow text-muted">OPERATOR / SHIPPING WORK</p><h1 className="mt-3 text-4xl font-black tracking-[-.08em]">배송 업무</h1><p className="mt-3 text-sm text-muted">합배송 요청을 확인하고 송장을 한 번에 입력하세요.</p></div>{notice && <div className="border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-700">{notice}</div>}<div className="grid gap-4 md:grid-cols-3"><div className="border border-line p-5"><p className="text-xs text-muted">요청 대기</p><p className="mt-3 font-mono text-3xl font-bold">{requests.length}</p></div><div className="border border-line p-5"><Truck size={17} /><p className="mt-7 text-xs text-muted">상품 합배송</p><p className="mt-3 font-mono text-3xl font-bold">{requests.reduce((sum, row) => sum + row.item_count, 0)}</p></div><div className="border border-line bg-surface p-5"><p className="text-xs text-muted">실제 DB 요청</p><p className="mt-3 font-mono text-3xl font-bold">{requests.length > 0 ? "LIVE" : "—"}</p></div></div><div className="border border-line"><div className="flex items-center justify-between border-b border-line bg-surface px-5 py-4"><p className="text-xs font-bold">배송 요청 목록</p><button className="flex items-center gap-2 border border-ink px-3 py-2 text-[10px] font-bold" onClick={download} type="button"><Download size={13} /> CSV 다운로드</button></div>{requests.map((row) => <div className="flex flex-col justify-between gap-4 border-b border-line px-5 py-5 last:border-b-0 md:flex-row md:items-center" key={row.request_id}><div><p className="text-sm font-bold">{row.request_id} · {row.item_count} items</p><p className="mt-1 text-xs text-muted">{row.requested_at} · {row.status}</p></div><div className="flex gap-2"><input className="h-10 w-32 border border-line px-3 text-xs" onChange={(event) => setForms({ ...forms, [row.request_id]: { ...(forms[row.request_id] ?? { courier: "", tracking: "" }), courier: event.target.value } })} placeholder="택배사" value={forms[row.request_id]?.courier ?? ""} /><input className="h-10 w-40 border border-line px-3 text-xs" onChange={(event) => setForms({ ...forms, [row.request_id]: { ...(forms[row.request_id] ?? { courier: "", tracking: "" }), tracking: event.target.value } })} placeholder="운송장 번호" value={forms[row.request_id]?.tracking ?? ""} /><button className="h-10 bg-ink px-4 text-xs font-bold text-paper" onClick={() => void ship(row.request_id)} type="button">발송 완료</button></div></div>)}{requests.length === 0 && <p className="py-16 text-center text-sm text-muted">배송 요청이 없습니다.</p>}</div></div>;
}
