"use client";

import Link from "next/link";
import { ArrowUpRight, Box, CircleDollarSign, MessageSquare, PackageCheck, Plus } from "lucide-react";
import { DEMO_PRODUCTS, DEMO_STORES } from "@/lib/catalog";

export function OperatorConsole() {
  const stats = [["오늘 공개 상품", "08", Box], ["입금 확인 대기", "03", CircleDollarSign], ["배송 요청", "05", PackageCheck], ["읽지 않은 상담", "02", MessageSquare]] as const;
  return <div className="space-y-10"><div className="flex flex-col justify-between gap-5 border-b border-ink pb-7 md:flex-row md:items-end"><div><p className="eyebrow text-muted">OPERATOR / CONTROL ROOM</p><h1 className="mt-3 text-4xl font-black tracking-[-0.08em]">운영자 센터</h1><p className="mt-3 text-sm text-muted">ARCHIVE 01 · JUN님의 오늘 업무를 확인하세요.</p></div><button className="flex items-center gap-2 bg-ink px-5 py-3 text-xs font-bold text-paper"><Plus size={15} /> 상품 등록</button></div><div className="grid gap-px border border-line bg-line md:grid-cols-4">{stats.map(([label, value, Icon]) => <div className="bg-paper p-5" key={label}><Icon size={17} /><p className="mt-7 text-xs text-muted">{label}</p><p className="mt-2 font-mono text-3xl font-bold">{value}</p></div>)}</div><div className="grid gap-10 lg:grid-cols-[1.25fr_.75fr]"><section><div className="mb-4 flex items-end justify-between border-b border-ink pb-4"><div><p className="eyebrow text-muted">MY STORE / PRODUCTS</p><h2 className="mt-2 text-xl font-black">내 숍 상품</h2></div><Link className="flex items-center gap-1 text-xs font-bold underline" href="/operator/products">전체 관리 <ArrowUpRight size={14} /></Link></div><div className="divide-y divide-line border-y border-line">{DEMO_PRODUCTS.filter((product) => product.store === DEMO_STORES[0]).map((product) => <div className="flex items-center gap-4 py-4" key={product.id}><img alt="" className="size-16 object-cover" src={product.imageUrls[0]} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{product.title}</p><p className="mt-1 text-xs text-muted">{product.saleType === "fixed" ? "즉시구매" : "경매"} · {product.price.toLocaleString("ko-KR")}원</p></div><span className="border border-emerald-200 bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-800">공개중</span></div>)}</div></section><section className="border border-line bg-surface p-6"><p className="eyebrow text-muted">TODAY / CHECKLIST</p><div className="mt-7 space-y-5 text-xs"><label className="flex gap-3"><input className="accent-ink" defaultChecked type="checkbox" /> 오늘 밤 드롭 이미지와 실측 확인</label><label className="flex gap-3"><input className="accent-ink" type="checkbox" /> 입금 확인 3건 처리</label><label className="flex gap-3"><input className="accent-ink" type="checkbox" /> 배송 요청 5건 송장 입력</label><label className="flex gap-3"><input className="accent-ink" type="checkbox" /> 상담 메시지 답변</label></div><Link className="mt-8 flex items-center justify-between border-t border-line pt-4 text-xs font-bold" href="/operator/shipping">배송 업무 열기 <ArrowUpRight size={14} /></Link></section></div></div>;
}

