import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root=new URL("../../",import.meta.url);const source=path=>readFile(new URL(path,root),"utf8");
test("owner settlement export is owner scoped and Excel safe",async()=>{const [route,button]=await Promise.all([source("src/app/api/admin/owner/settlement-export/route.ts"),source("src/components/admin/owner/ExportDataButton.tsx")]);assert.match(route,/authenticateOwnerAccessRequest/);assert.match(route,/store_settlement_entries/);assert.match(button,/\\uFEFF/);assert.match(button,/플랫폼수수료/);assert.match(button,/실정산지급액/);});
test("owner deposit confirmation requires a note in the atomic RPC",async()=>{const [migration,route,ui]=await Promise.all([source("supabase/migrations/20260822142248_add_owner_enterprise_operations.sql"),source("src/app/api/admin/operator/payments/[kind]/[id]/confirm/route.ts"),source("src/components/admin/operator/OperatorPaymentsConsole.tsx")]);assert.match(migration,/owner_confirm_manual_payment_with_note[\s\S]*confirm_unified_manual_payment_v2[\s\S]*write_security_activity/);assert.match(route,/owner_confirm_manual_payment_with_note/);assert.match(route,/approvalNote/);assert.match(ui,/입금 승인 메모/);});
test("owner onboarding is atomic and stores enterprise policy",async()=>{const [migration,route,ui]=await Promise.all([source("supabase/migrations/20260822142248_add_owner_enterprise_operations.sql"),source("src/app/api/admin/owner/stores/route.ts"),source("src/components/admin/owner/NewCenterModal.tsx")]);assert.match(migration,/store_enterprise_profiles/);assert.match(migration,/owner_onboard_store[\s\S]*manage_owner_store[\s\S]*store_payout_accounts/);assert.match(route,/action === "onboard"/);assert.match(route,/encryptAccountNumber/);assert.match(ui,/플랫폼 수수료율/);assert.match(ui,/소형 보관일/);});
test("penalties use existing append-only sanction history",async()=>{const [migration,route,ui]=await Promise.all([source("supabase/migrations/20260822142248_add_owner_enterprise_operations.sql"),source("src/app/api/admin/owner/penalties/route.ts"),source("src/components/admin/owner/PenaltyManagerTable.tsx")]);assert.match(migration,/owner_apply_bid_penalty[\s\S]*manage_member_sanction/);assert.match(route,/manual_transfer_orders/);assert.match(ui,/3일/);assert.match(ui,/7일/);assert.match(ui,/영구/);});
test("emergency controls remain protected by CONFIRM",async()=>{const [route,ui]=await Promise.all([source("src/app/api/admin/owner/auctions/emergency/route.ts"),source("src/components/admin/owner/OwnerEmergencyAuctionControl.tsx")]);assert.match(route,/body\.keyword !== "CONFIRM"/);assert.match(ui,/전사 \+1시간 연장/);});
test("operator platform server reads stay service-role-only and column-scoped",async()=>{const [migration,route]=await Promise.all([source("supabase/migrations/20260824201450_grant_operator_platform_server_reads.sql"),source("src/app/api/admin/operator/platform/route.ts")]);assert.match(migration,/grant select \([\s\S]*unpaid_fee_balance[\s\S]*\) on table public\.store_service_subscriptions to service_role/);assert.match(migration,/grant select \([\s\S]*business_address_detail[\s\S]*\) on table public\.store_enterprise_profiles to service_role/);assert.doesNotMatch(migration,/to (anon|authenticated)/i);assert.match(route,/auth\.admin\.from\("store_service_subscriptions"\)/);assert.match(route,/auth\.admin\.from\("store_enterprise_profiles"\)/);});
