"use client";

import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { ChevronDown, Mail, Phone } from "lucide-react";
import { useState } from "react";
import { CacheConsentSettings } from "@/components/layout/CacheConsentBanner";

export function PcFooter() {
  const [open, setOpen] = useState(false);
  const businessDetails = [["상호", "나인티 나인 빈티지"], ["대표", "이영준"], ["사업자등록번호", "875-07-03297"], ["업태 / 종목", "소매 / 의류"], ["사업장 주소", "부산광역시 수영구 수미로50번길 37-1, 1층"]] as const;
  return <footer className="border-t border-line bg-surface text-ink"><div className="mx-auto w-full max-w-[1440px] px-5 py-12 sm:px-8 xl:px-10"><div className="grid grid-cols-[1.2fr_.8fr_.8fr_1.5fr] gap-10"><section><Link className="text-xs font-black tracking-[0.12em]" href="/home">NINETY-NINE VINTAGE</Link><p className="mt-4 text-xs leading-5 text-muted">시간을 다시 입는 빈티지 경매 플랫폼</p><div className="mt-4 grid gap-2 text-xs"><a className="flex items-center gap-2 text-muted transition-colors hover:text-ink focus-visible:ring-2 focus-visible:ring-ink" href="tel:050714943519"><Phone size={14} strokeWidth={1.75} /> 0507-1494-3519</a><a className="flex items-center gap-2 text-muted transition-colors hover:text-ink focus-visible:ring-2 focus-visible:ring-ink" href="mailto:ninety-nine@kakao.com"><Mail size={14} strokeWidth={1.75} /> ninety-nine@kakao.com</a></div></section><section><p className="text-xs font-bold tracking-[0.1em]">서비스 안내</p><div className="mt-4 grid gap-3 text-xs text-muted"><Link className="hover:text-ink" href="/terms">이용약관</Link><Link className="hover:text-ink" href="/privacy">개인정보처리방침</Link><Link className="hover:text-ink" href="/refund">환불·취소 정책</Link></div></section><section><p className="text-xs font-bold tracking-[0.1em]">내 계정</p><div className="mt-4 grid gap-3 text-xs text-muted"><Link className="hover:text-ink" href="/my">내 정보</Link><Link className="hover:text-ink" href="/my/orders">주문·배송</Link><Link className="hover:text-ink" href="/my/vault">보관함</Link><Link className="hover:text-ink" href="/chat">상담·채팅</Link></div></section><section><button aria-controls="business-details" aria-expanded={open} className="flex w-full items-center justify-between rounded-xl text-left text-xs font-bold tracking-[0.1em] focus-visible:ring-2 focus-visible:ring-ink focus-visible:ring-offset-4" onClick={() => setOpen((value) => !value)} type="button"><span>사업자 정보</span><ChevronDown className={`transition-transform duration-200 ${open ? "rotate-180" : ""}`} size={16} strokeWidth={1.75} /></button><AnimatePresence initial={false}>{open && <motion.dl animate={{ height: "auto", opacity: 1 }} className="mt-4 grid grid-cols-[7rem_1fr] gap-x-4 gap-y-2 overflow-hidden text-xs leading-5" exit={{ height: 0, opacity: 0 }} id="business-details" initial={{ height: 0, opacity: 0 }} transition={{ duration: .24, ease: "easeOut" }}>{businessDetails.map(([label, value]) => <div className="contents" key={label}><dt className="text-muted">{label}</dt><dd>{value}</dd></div>)}</motion.dl>}</AnimatePresence></section></div><div className="mt-10 flex items-start justify-between gap-8 border-t border-line pt-5"><p className="pt-1 text-[10px] text-muted">© 2026 NINETY-NINE VINTAGE. 모든 권리 보유.</p><CacheConsentSettings /></div></div></footer>;
}
