"use client";
import {Cog,Heart,LogOut,Package,Truck,Gavel,X} from "lucide-react";
import {useRouter} from "next/navigation";
import {useEffect,useState} from "react";
import {useSupabaseSession} from "@/hooks/useSupabaseSession";
import {getSupabaseBrowserClient} from "@/lib/supabase/client";
import {PremiumDialog} from "@/components/ui/PremiumDialog";
import {useCommerceStore} from "@/store/useCommerceStore";
export type MyTab="home"|"vault"|"auction"|"orders"|"wishlist"|"settings";
interface Metrics{vault:number;bids:number;wins:number;shipping:number;risk:boolean}
export function ProfileHeader({activeTab,onTabChange,basePath=""}:{activeTab:MyTab;onTabChange:(tab:MyTab)=>void;basePath?:""|"/m"}){const router=useRouter();const{session}=useSupabaseSession();const liked=useCommerceStore(s=>s.likedIds.length);const[metrics,setMetrics]=useState<Metrics>({vault:0,bids:0,wins:0,shipping:0,risk:false});const[logoutOpen,setLogoutOpen]=useState(false);const user=session?.user;const nickname=user?.user_metadata?.name??user?.user_metadata?.full_name??"빈티지 피플";const email=user?.email?.replace(/^(.{2}).*(@.*)$/u,"$1**$2")??"카카오 회원";
useEffect(()=>{if(!session?.access_token)return;const headers={Authorization:`Bearer ${session.access_token}`};void Promise.all([fetch("/api/account/storage",{headers,cache:"no-store"}),fetch("/api/account/bids",{headers,cache:"no-store"}),fetch("/api/account/shipments",{headers,cache:"no-store"})]).then(async([storage,bids,shipments])=>{const s=storage.ok?await storage.json():{};const b=bids.ok?await bids.json():{};const h=shipments.ok?await shipments.json():{};const items=Array.isArray(s.items)?s.items:[];setMetrics({vault:items.length,bids:Number(b.summary?.leading??0)+Number(b.summary?.outbid??0),wins:Number(b.summary?.final??0),shipping:Array.isArray(h.shipments)?h.shipments.filter((row:{status?:string})=>row.status!=="delivered").length:0,risk:items.some((row:{storage_expires_at?:string})=>{const days=(Date.parse(row.storage_expires_at??"")-Date.now())/86400000;return days>=0&&days<=3})})}).catch(()=>undefined)},[session]);
const cards=[{tab:"vault" as const,label:"보관함",value:metrics.vault,Icon:Package,risk:metrics.risk},{tab:"auction" as const,label:"참여 옥션",value:metrics.bids+metrics.wins,Icon:Gavel,risk:metrics.wins>0},{tab:"orders" as const,label:"주문/배송",value:metrics.shipping,Icon:Truck,risk:false},{tab:"wishlist" as const,label:"찜 목록",value:liked,Icon:Heart,risk:false}];const logout=async()=>{await getSupabaseBrowserClient().auth.signOut();router.replace(`${basePath}/home`);router.refresh()};
return <><header className="rounded-3xl border border-zinc-800 bg-zinc-950 p-5 text-zinc-100 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-5"><div className="flex items-center gap-4"><div className="relative grid size-16 place-items-center rounded-full bg-zinc-800 text-xl font-black">{String(nickname).slice(0,1)}<span className="absolute -bottom-1 -right-1 rounded-full bg-[#FEE500] px-2 py-1 text-[8px] font-black text-black">KAKAO</span></div><div><h1 className="text-2xl font-black tracking-[-.05em]">{nickname}</h1><p className="mt-1 text-xs text-zinc-400">{email}</p><p className="mt-1 font-mono text-[10px] text-zinc-500">MEMBER SINCE {user?.created_at?new Date(user.created_at).toLocaleDateString("ko-KR"):"-"}</p></div></div><div className="flex gap-2"><button aria-label="계정 설정" className="grid size-11 place-items-center rounded-xl border border-zinc-700" onClick={()=>onTabChange("settings")} type="button"><Cog size={17}/></button><button className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-zinc-700 px-4 text-xs font-bold" onClick={()=>setLogoutOpen(true)} type="button"><LogOut size={15}/>로그아웃</button></div></div><div className="mt-7 grid grid-cols-2 gap-2 lg:grid-cols-4">{cards.map(({tab,label,value,Icon,risk})=><button aria-current={activeTab===tab?"page":undefined} className={`relative rounded-2xl border p-4 text-left transition hover:-translate-y-0.5 ${activeTab===tab?"border-amber-500 bg-zinc-900":"border-zinc-800 bg-zinc-900/60"}`} key={tab} onClick={()=>onTabChange(tab)} type="button"><Icon size={18}/>{risk?<span className="absolute right-3 top-3 size-2 animate-pulse rounded-full bg-rose-500"/>:null}<p className="mt-5 text-[10px] text-zinc-400">{label}</p><p className="mt-2 font-mono text-2xl font-black">{value}</p></button>)}</div></header><PremiumDialog labelledBy="my-logout-title" onClose={()=>setLogoutOpen(false)} open={logoutOpen} panelClassName="max-w-md"><div className="flex items-start justify-between border-b border-line p-5"><h2 className="text-xl font-black" id="my-logout-title">로그아웃하시겠습니까?</h2><button aria-label="닫기" onClick={()=>setLogoutOpen(false)} type="button"><X/></button></div><div className="p-5"><p className="text-sm text-muted">진행 중인 결제나 배송 신청 내용을 확인한 뒤 로그아웃해 주세요.</p><div className="mt-6 grid grid-cols-2 gap-2"><button className="min-h-11 border border-line font-bold" onClick={()=>setLogoutOpen(false)} type="button">취소</button><button className="min-h-11 bg-ink font-bold text-paper" onClick={()=>void logout()} type="button">로그아웃</button></div></div></PremiumDialog></>}
