"use client";

import { X } from "lucide-react";
import { useEffect, useState } from "react";
import { PremiumDialog } from "@/components/ui/PremiumDialog";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Option={id:string;name?:string;displayName?:string;assignable?:boolean};
export function NewCenterModal({open,onClose,onCreated}:{open:boolean;onClose:()=>void;onCreated:()=>void}){
 const [businesses,setBusinesses]=useState<Option[]>([]);const [operators,setOperators]=useState<Option[]>([]);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
 const [form,setForm]=useState({businessId:"",operatorId:"",slug:"",name:"",description:"",representativeName:"",businessRegistrationNumber:"",bankName:"",accountHolder:"",accountNumber:"",smallStorageDays:"14",largeStorageDays:"7"});
 useEffect(()=>{if(!open)return;void (async()=>{const session=(await getSupabaseBrowserClient().auth.getSession()).data.session;if(!session)return;const response=await fetch("/api/admin/owner/stores",{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"});const payload=await response.json() as {management?:{businesses?:Option[];operators?:Option[]}};const nextBusinesses=payload.management?.businesses??[];const nextOperators=(payload.management?.operators??[]).filter(option=>option.assignable);setBusinesses(nextBusinesses);setOperators(nextOperators);setForm(current=>({...current,businessId:current.businessId||nextBusinesses[0]?.id||"",operatorId:current.operatorId||nextOperators[0]?.id||""}));})();},[open]);
 const set=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}));
 const submit=async()=>{setBusy(true);setNotice("");try{const session=(await getSupabaseBrowserClient().auth.getSession()).data.session;if(!session)throw new Error("로그인이 필요합니다.");const response=await fetch("/api/admin/owner/stores",{method:"PATCH",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({action:"onboard",idempotencyKey:crypto.randomUUID(),...form,smallStorageDays:Number(form.smallStorageDays),largeStorageDays:Number(form.largeStorageDays)})});const payload=await response.json() as {message?:string};if(!response.ok)throw new Error(payload.message??"센터를 등록하지 못했습니다.");onCreated();onClose();}catch(error){setNotice(error instanceof Error?error.message:"센터를 등록하지 못했습니다.");}finally{setBusy(false);}};
 const valid=form.businessId&&form.operatorId&&/^[a-z0-9-]{2,80}$/.test(form.slug)&&form.name.trim()&&form.representativeName.trim()&&/^\d{10}$/.test(form.businessRegistrationNumber.replace(/\D/g,""))&&form.bankName.trim()&&form.accountHolder.trim()&&form.accountNumber.trim();
 return <PremiumDialog closeDisabled={busy} labelledBy="new-center-title" onClose={onClose} open={open} panelClassName="max-w-3xl border-zinc-700 bg-zinc-950 p-5 text-zinc-100 sm:p-7" zIndexClassName="z-[150]"><div className="flex items-start justify-between"><div><p className="text-xs font-black text-amber-400">판매센터 온보딩</p><h2 className="mt-2 text-2xl font-black" id="new-center-title">신규 판매센터 등록</h2></div><button aria-label="닫기" className="grid size-11 place-items-center" disabled={busy} onClick={onClose} type="button"><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{[["센터명","name","나인티나인 부산"],["센터 코드","slug","ninety-nine-busan"],["대표자명","representativeName","홍길동"],["사업자등록번호","businessRegistrationNumber","1234567890"],["은행명","bankName","국민은행"],["예금주","accountHolder","홍길동"],["정산 계좌번호","accountNumber","숫자 계좌번호"],["소형 보관일","smallStorageDays","14"],["대형 보관일","largeStorageDays","7"]].map(([label,key,placeholder])=><label className="text-xs font-bold" key={key}>{label}<input className="mt-2 h-11 w-full rounded-xl border border-zinc-700 bg-zinc-900 px-3" inputMode={["businessRegistrationNumber","accountNumber","smallStorageDays","largeStorageDays"].includes(key)?"numeric":undefined} onChange={event=>set(key as keyof typeof form,event.target.value)} placeholder={placeholder} value={form[key as keyof typeof form]}/></label>)}<div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-xs font-bold text-emerald-300">플랫폼 판매 수수료는 센터 등급과 관계없이 5%로 고정됩니다.</div><label className="text-xs font-bold">사업체<select className="mt-2 h-11 w-full rounded-xl border border-zinc-700 bg-zinc-900 px-3" onChange={event=>set("businessId",event.target.value)} value={form.businessId}>{businesses.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-xs font-bold">담당 운영자<select className="mt-2 h-11 w-full rounded-xl border border-zinc-700 bg-zinc-900 px-3" onChange={event=>set("operatorId",event.target.value)} value={form.operatorId}>{operators.map(item=><option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label className="text-xs font-bold sm:col-span-2">센터 설명<textarea className="mt-2 min-h-20 w-full rounded-xl border border-zinc-700 bg-zinc-900 p-3" onChange={event=>set("description",event.target.value)} value={form.description}/></label></div>{notice&&<p className="mt-4 text-xs text-rose-400">{notice}</p>}<div className="mt-6 flex justify-end gap-2 pb-[max(0rem,env(safe-area-inset-bottom))]"><button className="min-h-11 px-4 text-xs font-bold" disabled={busy} onClick={onClose} type="button">취소</button><button className="min-h-11 rounded-xl bg-amber-500 px-5 text-xs font-black text-foreground disabled:opacity-40" disabled={busy||!valid} onClick={()=>void submit()} type="button">{busy?"등록 중…":"센터 등록"}</button></div></PremiumDialog>;
}
