"use client";

import { AlertTriangle, Clock3, PauseCircle, PlayCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Action = "pause" | "resume" | "extend_60";

export function OwnerEmergencyAuctionControl() {
  const [token, setToken] = useState(""); const [paused, setPaused] = useState(false); const [pending, setPending] = useState<Action | null>(null);
  const [keyword, setKeyword] = useState(""); const [reason, setReason] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void (async () => { const session = (await getSupabaseBrowserClient().auth.getSession()).data.session; if (!session) return; setToken(session.access_token); const response = await fetch("/api/admin/owner/auctions/emergency", { headers: { Authorization: `Bearer ${session.access_token}` }, cache: "no-store" }); const data = await response.json() as { paused?: boolean }; if (response.ok) setPaused(data.paused === true); else setNotice("비상 제어 상태를 불러오지 못했습니다."); })(); }, []);
  const run = async () => { if (!pending || busy) return; setBusy(true); setNotice(""); const response = await fetch("/api/admin/owner/auctions/emergency", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ action: pending, reason, keyword }) }); const data = await response.json() as { message?: string; result?: { paused?: boolean } }; setBusy(false); if (!response.ok) { setNotice(data.message ?? "비상 제어를 실행하지 못했습니다."); return; } setPaused(data.result?.paused === true); setPending(null); setKeyword(""); setReason(""); setNotice("전사 경매 제어 작업과 감사 기록을 완료했습니다."); };
  return <section className="rounded-2xl border border-rose-500/30 bg-zinc-950 p-5 text-zinc-100"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-black text-rose-400"><AlertTriangle size={15} /> Emergency control room</p><h1 className="mt-2 text-2xl font-black">전사 경매 비상 제어</h1><p className="mt-2 text-xs text-zinc-500">모든 센터의 신규 입찰을 DB에서 차단하며, 재개 시 중단 시간을 활성 경매 마감에 반영합니다.</p></div><span className={`rounded-full border px-3 py-2 text-xs font-black ${paused ? "border-rose-500/40 bg-rose-500/10 text-rose-400" : "border-emerald-500/30 text-emerald-400"}`}>{paused ? "일시정지 중" : "정상 운영"}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><button className="min-h-11 rounded-xl bg-rose-600 px-4 text-xs font-black" onClick={() => setPending("pause")} type="button"><PauseCircle className="mr-2 inline" size={15} />비상 일괄 정지</button><button className="min-h-11 rounded-xl border border-emerald-500/30 px-4 text-xs font-black text-emerald-400" onClick={() => setPending("resume")} type="button"><PlayCircle className="mr-2 inline" size={15} />경매 재개</button><button className="min-h-11 rounded-xl border border-amber-500/30 px-4 text-xs font-black text-amber-400" onClick={() => setPending("extend_60")} type="button"><Clock3 className="mr-2 inline" size={15} />전사 +1시간 연장</button></div>{pending && <div className="mt-5 rounded-xl border border-zinc-700 bg-zinc-900 p-4"><p className="text-sm font-black">2단계 확인</p><textarea className="mt-3 min-h-24 w-full rounded-xl border border-zinc-700 bg-zinc-950 p-3 text-xs" onChange={(event) => setReason(event.target.value)} placeholder="감사 로그에 남길 필수 사유" value={reason} /><input className="mt-3 h-11 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-3 font-mono text-xs" onChange={(event) => setKeyword(event.target.value)} placeholder="CONFIRM 입력" value={keyword} /><div className="mt-3 flex justify-end gap-2"><button className="min-h-11 px-4 text-xs font-bold" onClick={() => setPending(null)} type="button">취소</button><button className="min-h-11 rounded-xl bg-rose-600 px-4 text-xs font-black disabled:opacity-40" disabled={busy || keyword !== "CONFIRM" || reason.trim().length < 2} onClick={() => void run()} type="button">{busy ? "처리 중…" : "확인 후 실행"}</button></div></div>}{notice && <p aria-live="polite" className="mt-4 text-xs text-zinc-400">{notice}</p>}</section>;
}
