"use client";

import { Heart, Search, ShieldCheck, Store, UsersRound } from "lucide-react";
import Link from "next/link";
import { useDeferredValue, useMemo, useState } from "react";
import { CatalogImage } from "@/components/ui/CatalogImage";
import type { StoreMallCard } from "@/services/stores";

const filters = ["전체", "실시간 경매 진행중", "아메카지/워크웨어", "하이엔드/디자이너", "올드스쿨/스포츠", "밀리터리/유러피안"] as const;

export function CenterMallHub({ cards, routeBase = "/centers" }: { cards: StoreMallCard[]; routeBase?: "/centers" | "/stores" | "/m/centers" | "/m/stores" }) {
  const [query, setQuery] = useState(""); const deferredQuery = useDeferredValue(query.trim().toLocaleLowerCase("ko-KR")); const [filter, setFilter] = useState<(typeof filters)[number]>("전체"); const [sort, setSort] = useState("popular");
  const visible = useMemo(() => cards.filter((card) => { const text = `${card.name} ${card.description} ${card.mallInfo ?? ""}`.toLocaleLowerCase("ko-KR"); if (deferredQuery && !text.includes(deferredQuery)) return false; if (filter === "실시간 경매 진행중") return card.liveAuctionCount > 0; if (filter !== "전체") return text.includes(filter.split("/")[0]); return true; }).toSorted((a, b) => sort === "latest" ? b.recentCount - a.recentCount : sort === "products" ? b.totalCount - a.totalCount : b.liveAuctionCount - a.liveAuctionCount || b.totalCount - a.totalCount), [cards, deferredQuery, filter, sort]);
  return <div className="space-y-8"><section className="rounded-3xl border border-zinc-800 bg-zinc-950 p-5 text-zinc-100"><div className="grid gap-3 md:grid-cols-[1fr_auto]"><label className="flex min-h-12 items-center gap-3 rounded-2xl border border-zinc-700 bg-zinc-900 px-4 focus-within:border-amber-500"><Search size={18} /><input aria-label="센터명, 무드, 콘셉트 검색" className="min-w-0 flex-1 bg-transparent text-sm outline-none" onChange={(event) => setQuery(event.target.value)} placeholder="센터명·무드·콘셉트 검색" value={query} /></label><select aria-label="센터 정렬" className="min-h-12 rounded-2xl border border-zinc-700 bg-zinc-900 px-4 text-xs font-bold" onChange={(event) => setSort(event.target.value)} value={sort}><option value="popular">인기순</option><option value="latest">최신순</option><option value="products">등록 상품 많은 순</option><option value="rating">평점 높은 순</option></select></div><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{filters.map((item) => <button className={`min-h-10 shrink-0 rounded-full border px-4 text-xs font-bold ${filter === item ? "border-amber-500 bg-amber-500 text-zinc-950" : "border-zinc-700 text-zinc-400"}`} key={item} onClick={() => setFilter(item)} type="button">{item === "실시간 경매 진행중" ? "🔥 " : ""}{item}</button>)}</div></section>{visible.length ? <section aria-label="판매 센터 목록" className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visible.map((card) => <CenterCard card={card} key={card.id} routeBase={routeBase} />)}</section> : <div className="rounded-3xl border border-dashed border-zinc-700 py-20 text-center text-sm text-muted">조건에 맞는 센터가 없습니다.</div>}</div>;
}

function CenterCard({ card, routeBase }: { card: StoreMallCard; routeBase: string }) {
  const [followed, setFollowed] = useState(false); const href = `${routeBase}/${encodeURIComponent(card.slug)}`;
  return <article className="group overflow-hidden rounded-3xl border border-zinc-800 bg-zinc-900 text-zinc-100 transition-transform duration-300 hover:-translate-y-1"><div className="relative aspect-video bg-zinc-800">{card.mallImage ? <CatalogImage alt={`${card.name} 센터 커버`} className="size-full object-cover transition-transform duration-500 group-hover:scale-[1.03]" sizes="(max-width: 768px) 100vw, 33vw" src={card.mallImage} /> : null}<div className="absolute inset-0 bg-gradient-to-t from-zinc-950 via-transparent to-black/20" /><span className={`absolute right-4 top-4 rounded-full border px-3 py-2 text-[10px] font-black ${card.liveAuctionCount ? "border-rose-500/40 bg-rose-500/15 text-rose-300" : "border-zinc-600 bg-zinc-950/70 text-zinc-400"}`}><span className={`mr-2 inline-block size-2 rounded-full ${card.liveAuctionCount ? "animate-pulse bg-rose-500" : "bg-zinc-500"}`} />{card.liveAuctionCount ? "LIVE 경매 진행중" : "경매 준비중"}</span><span className="absolute -bottom-7 left-5 grid size-16 place-items-center rounded-full border-4 border-zinc-900 bg-amber-500 text-xl font-black text-zinc-950">{card.name.slice(0, 1)}</span></div><div className="p-5 pt-11"><div className="flex items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-black">{card.name}<ShieldCheck className="text-sky-400" size={16} /></h2><p className="mt-2 line-clamp-2 text-xs leading-5 text-zinc-400">{card.mallInfo ?? card.description}</p></div><button aria-pressed={followed} aria-label={`${card.name} 단골 ${followed ? "해제" : "등록"}`} className={`grid size-11 place-items-center rounded-full border ${followed ? "border-rose-500 text-rose-400" : "border-zinc-700"}`} onClick={() => setFollowed((value) => !value)} type="button"><Heart fill={followed ? "currentColor" : "none"} size={18} /></button></div><div className="mt-5 grid grid-cols-3 gap-2 font-mono text-[10px] text-zinc-400"><span><Store className="mb-1" size={14} />상품 {card.totalCount}</span><span><UsersRound className="mb-1" size={14} />신규 {card.recentCount}</span><span>★ —<br />후기 준비중</span></div><div className="mt-5 flex gap-2">{card.previewImages.map((src, index) => <CatalogImage alt={`${card.name} 상품 미리보기 ${index + 1}`} className="aspect-square w-14 rounded-xl object-cover" key={`${src}-${index}`} sizes="56px" src={src} />)}</div><Link className="mt-5 flex min-h-11 items-center justify-center rounded-xl bg-zinc-100 text-xs font-black text-zinc-950" href={href}>센터 방문하기</Link></div></article>;
}
